spring:
  # 프로필 포함 설정: application-oauth.yml 파일을 활성화합니다.
  profiles:
    include: oauth

  # ANSI 컬러 로그 출력 활성화
  output:
    ansi:
      enabled: ALWAYS

# 머스테치 인코딩 설정 추가
  mustache:
    charset: UTF-8

  # H2 데이터베이스 설정 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:happeneddb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# 서버 인코딩 설정
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

