spring:
  # 프로필 포함 설정: application-oauth.yml 파일을 활성화합니다.
  profiles:
    include: oauth

  output:
    ansi:
      enabled: ALWAYS

  mustache:
    charset: UTF-8

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:happeneddb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
